language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

sudo: false

matrix:
  fast_finish: true

install:
  - pip install tox tox-travis
  - pip install coveralls

script:
  - tox

after_success:
  - coveralls

notifications:
  email: false
