name: Qlty Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage

    - name: Test with coverage reporting
      run: coverage run -m unittest discover -s tests
  
    - name: Export coverage data as LCOV
      run: coverage lcov -o coverage.lcov
    
    - name: Upload coverage data to Qlty Cloud
      uses: qltysh/qlty-action/coverage@v1
      with:
        oidc: true
        verbose: true
        files: coverage.lcov
